defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: workerapp_development

test:
  <<: *defaults
  database: workerapp_test

staging:
  uri: <%= ENV['MONGOHQ_URL'] %>

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
